version: "15.0.0"
state: 0


# Punishment commands
command:
  kick: "kick {player} &cYou have been removed from the game based on data that was collected by the anti-cheat ({log-id})"
  ban: "ban {player} &cYou have been removed from the game based on data that was collected by the anti-cheat ({log-id})"

# You should disable any of these options **ONLY**
# when experiencing serious problems and **ONLY** after reporting the issue to us.
# Leaving any of these disabled can result in severely reduced security and stability.
fault-kicks:
  position-faults: true
  missing-position-update: true
  feedback-faults: true
  ignoring-feedback: true
  ignoring-keep-alive: true
  invalid-key-input: true
  invalid-player-action: true

logging:
  # Save logs to a file?
  file-log: true

  # Show trustfactor changes in the console?
  trustfactor: true
  # Show client version on join in the console?
  client-version: true
  # Show command executions in the console?
  command-execution: true
  # Show fault kicks in the console?
  fault-kicks: true
  # Dump player log ids in the console?
  cloud-log-ids: true
  # Verbose mode (ALL, MITIGATED, SELECTED)
  verbose-mode: MITIGATED

layout:
  verbose: "{prefix} &c{player}&7/{trust-color}&7 {message} {details} (+{vladded} -> {vl})"
  notify: "{prefix} &c&lNotify&8: &7{text}"
  prefix: "&8[&c&lIntave&8]&7 "